apiVersion: apps/v1
kind: Deployment
metadata:
  name: root-agent
  namespace: mult-agent
  labels:
    app: root-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: root-agent
  template:
    metadata:
      labels:
        app: root-agent
    spec:
      containers:
      - name: root-agent
        image: multi-agent/root-agent:latest
        ports:
        - containerPort: 8000
        env:
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: llm-secrets
              key: google-api-key
              optional: true
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq-service:5672/"
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5