apiVersion: v1
kind: Service
metadata:
  name: root-agent-service
  namespace: multi-agent
  labels:
    app: root-agent
spec:
  selector:
    app: root-agent
spec:
  selector:
    app: root-agent
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP