apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: multi-agent
data:
  rabbitmq.conf: |
    default_user = guest
    default_pass = guest
    default_vhost = /
    default_user_tags.adminstrator = true
    default_permissions.configure = .*
    default_permissions.read = .*
    default_permissions.write = .*