apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: multi-agent
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq