apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: search-agent-hpa
  namespace: multi-agent
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: search-agent
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70